hard_tabs = true
tab_spaces = 4
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
indent_style = "Block"
fn_params_layout = "Tall"
match_block_trailing_comma = false
empty_item_single_line = false
use_small_heuristics = "Off"
