name: CI

on:
  push:
    branches:
      - dev/server
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Add Rust to PATH (if needed)
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build the project
        run: make

      - name: Run checks (todo)
        run: true
