name: Build and Release Windows Server

on:
  push:
    branches:
      - main
      - windows
      - server

jobs:
  build:
    name: Build Windows Server
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Build server only
        run: make server

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-windows
          path: bin/server.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: server-windows
          path: .

      - name: Generate dynamic tag
        id: tag
        run: echo "TAG=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Server ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          files: ./server.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
